# -*- coding: utf-8 -*-
"""Brain weight in humans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LWLKkq8yoS9DMRUA6OMUAnCsdJstI5UI
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

"""+ Gender : 1 represents Male , 2 represents Female

+ Age Range : 1 represents >18 years of age , 2 represents <18 years of age

+ Head Size(cm^3)

+ Brain Weight(grams)
"""

data = pd.read_csv("dataset.csv")
data

model = LinearRegression()
model.fit(data[['Gender', 'Age Range', 'Head Size(cm^3)']], data['Brain Weight(grams)'])

model.predict([[1,1,4177]])

model.coef_

model.intercept_

y_new = model.coef_[0]*1 + model.coef_[1]*1 + model.coef_[2]*4177+model.intercept_
y_new

model = LinearRegression()
model.fit(data[['Brain Weight(grams)', 'Age Range', 'Head Size(cm^3)']], data.Gender)

model.predict([[1438,1,4177]])

model.predict([[1110,2,3214]])

model.predict([[1530,1,4512]])

model.predict([[1170,2,3352]])

